apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mqtt/
  - nodered/
  - provisioning-api/
  - rollout/
  - ../../../namespaces/iot-namespaces.yaml
  - ../../../base/iot

commonLabels:
  environment: prod

patches:
  - target:
      kind: Namespace
      name: iot
    patch: |-
      - op: add
        path: /metadata/annotations/linkerd.io~1inject
        value: enabled
