apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/runtime-namespaces.yaml
  - apps/immich/kustomization.yaml
  - apps/nextcloud/kustomization.yaml
  - apps/postgres/statefulset.yaml
  - apps/api/api-stack.yaml
  - apps/n8n/n8n-stack.yaml
  - infra/backup/cronjob.yaml
