apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/runtime-namespaces.yaml
  - apps/api/api-stack.yaml
  - apps/n8n/templates/n8n-stack.yaml
  - apps/rabbitmq/templates/rabbitmq-stack.yaml
  - apps/postgres/templates/cluster-ha.yaml
  - infra/backup/cronjob.yaml
