apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mqtt-secret
  namespace: iot
spec:
  target:
    name: mqtt-secret
  data:
    - secretKey: username
      remoteRef:
        key: mqtt/user
    - secretKey: password
      remoteRef:
        key: mqtt/pass
