apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

helmCharts:
  - name: nextcloud
    repo: https://nextcloud.github.io/helm/
    version: 5.0.0
    releaseName: nextcloud
    namespace: apps
    valuesFile: values.yaml
