apiVersion: v1
kind: Namespace
metadata:
  name: iot
  labels:
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iot-sa
  namespace: iot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: iot
  name: iot-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iot-binding
  namespace: iot
subjects:
  - kind: ServiceAccount
    name: iot-sa
roleRef:
  kind: Role
  name: iot-role
  apiGroup: rbac.authorization.k8s.io
